version: '3'
services:
  api:
    build: ./.docker/api
    
  db:
    build: ./.docker/mysql
    user: "1000:1000"
    restart: always
    volumes:
      #  Mount DB inside container to prevent data loose.
      - "./.docker/mysql/data:/var/lib/mysql"
    ports:
      - "127.0.1.3:3306:3306"
    environment:
      # Only password make sense if you mount you DB with "volumes".
      - MYSQL_ROOT_PASSWORD=sapp
      - MYSQL_DATABASE=sapp
    networks:
      - app
networks:
  app:
    driver: bridge

