version: '3'
services:
  api:
    build: ./.docker/api
    user: "1000:www-data"
    restart: always
    volumes:
      #  Mount DB inside container to prevent data loose.
      - ".:/var/www/html"
    ports:
      - 127.0.1.2:80:80
  composer_be:
    restart: "no"
    build:
      context: ./.docker/api
      dockerfile: DockerfileComposer
    command: "composer up"
    depends_on:
      - api
    volumes:
      - ".:/var/www/html"
#    networks:
#      - app
  db:
    build: ./.docker/db
    user: "1000:1000"
    restart: always
    volumes:
      #  Mount DB inside container to prevent data loose.
      - "./.docker/db/data:/var/lib/mysql"
    ports:
      - "127.0.1.3:3306:3306"
    environment:
      # Only password make sense if you mount you DB with "volumes".
      - MYSQL_ROOT_PASSWORD=sapp
      - MYSQL_DATABASE=sapp
    networks:
      - app
networks:
  app:
    driver: bridge

